routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\LogoutController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\CarController;
use App\Http\Controllers\PartController;


Route::get('/', function () {return view('welcome');})->name('index');

Route::resource('cars', CarController::class);
Route::resource('parts', PartController::class);


/**
 * Authentification
 */
Route::group(['middleware' => ['guest']], function() {
    /**
     * Register Routes
     */
    Route::get('/register', [RegisterController::class, 'show'])->name('register.show');
    Route::post('/register', [RegisterController::class, 'register'])->name('register.perform');

    /**
     * Login Routes
     */
    Route::get('/login', [LoginController::class, 'show'])->name('login.show');
    Route::post('/login', [LoginController::class, 'login'])->name('login.perform');

});

Route::group(['middleware' => ['auth']], function() {
    /**
     * Logout Routes
     */
    Route::get('/logout', [LogoutController::class, 'perform'])->name('logout.perform');
});

app/Models/Part.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Part extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'serialnumber', 'car_id'];

    public function car()
    {
        return $this->belongsTo(Car::class);
    }    
}

app/Http/Controllers/PartController.php
<?php

namespace App\Http\Controllers;

use App\Models\Part;
use App\Models\Car;
use Illuminate\Http\Request;

class PartController extends Controller
{
    /**
     * Display a listing of the parts.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //$parts = Part::all();
        $parts = Part::with('car')->get();
        return view('parts.index', compact('parts'));
    }

    /**
     * Show the form for creating a new part.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $cars = Car::all(); // Získanie zoznamu áut pre výber pri vytváraní dielu
        return view('parts.create', compact('cars'));
    }

    /**
     * Store a newly created part in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'name' => 'required',
            'serialnumber' => 'required',
            'car_id' => 'required|exists:cars,id', // Skontroluje, či zadané ID auta existuje
        ]);

        Part::create($validatedData);

        return redirect()->route('parts.index');
    }

    /**
     * Display the specified part.
     *
     * @param  \App\Models\Part  $part
     * @return \Illuminate\Http\Response
     */
    public function show(Part $part)
    {
        return view('parts.show', compact('part'));
    }

    /**
     * Show the form for editing the specified part.
     *
     * @param  \App\Models\Part  $part
     * @return \Illuminate\Http\Response
     */
    public function edit(Part $part)
    {
        $cars = Car::all();
        return view('parts.edit', compact('part', 'cars'));
    }

    /**
     * Update the specified part in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Part  $part
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Part $part)
    {
        $validatedData = $request->validate([
            'name' => 'required',
            'serialnumber' => 'required',
            'car_id' => 'required|exists:cars,id',
        ]);

        $part->update($validatedData);

        return redirect()->route('parts.index');
    }

    /**
     * Remove the specified part from storage.
     *
     * @param  \App\Models\Part  $part
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $part = Part::findOrFail($id);
        $part->delete();
        return response()->json(['message' => 'Part deleted successfully.']);
    }    
}

resources/views/parts/create.blade.php
{{-- resources/views/parts/create.blade.php --}}

@extends('layouts.app')

@section('title', 'Add New Part')

@section('content')
<div class="container mt-4">
    <h1>Add New Part</h1>
    <form method="POST" action="{{ route('parts.store') }}">
        @csrf
        <div class="mb-3">
            <label for="name" class="form-label">Part Name</label>
            <input type="text" class="form-control" id="name" name="name" required>
        </div>
        <div class="mb-3">
            <label for="serialnumber" class="form-label">Serial Number</label>
            <input type="text" class="form-control" id="serialnumber" name="serialnumber" required>
        </div>
        <div class="mb-3">
            <label for="car_id" class="form-label">Car</label>
            <select class="form-select" id="car_id" name="car_id">
                @foreach ($cars as $car)
                    <option value="{{ $car->id }}">{{ $car->name }}</option>
                @endforeach
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
@endsection

resources/views/parts/edit.blade.php
{{-- resources/views/parts/edit.blade.php --}}

@extends('layouts.app')

@section('title', 'Edit Part')

@section('content')
<div class="container mt-4">
    <h1>Edit Part</h1>
    <form method="POST" action="{{ route('parts.update', $part) }}">
        @csrf
        @method('PUT')
        <div class="mb-3">
            <label for="name" class="form-label">Part Name</label>
            <input type="text" class="form-control" id="name" name="name" value="{{ $part->name }}" required>
        </div>
        <div class="mb-3">
            <label for="serialnumber" class="form-label">Serial Number</label>
            <input type="text" class="form-control" id="serialnumber" name="serialnumber" value="{{ $part->serialnumber }}" required>
        </div>
        <div class="mb-3">
            <label for="car_id" class="form-label">Car</label>
            <select class="form-select" id="car_id" name="car_id">
                @foreach ($cars as $car)
                    <option value="{{ $car->id }}" {{ $car->id == $part->car_id ? 'selected' : '' }}>{{ $car->name }}</option>
                @endforeach
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
@endsection

resources/views/parts/index.blade.php
{{-- resources/views/parts/index.blade.php --}}

@extends('layouts.app')

@section('title', 'Parts List')

@section('content')
    <h1>Parts</h1>
        <a href="{{ route('index') }}" class="btn btn-secondary me-2">Home</a>
        <a href="{{ route('cars.index') }}" class="btn btn-secondary me-2">View Cars</a>
        <a href="{{ route('parts.create') }}" class="btn btn-primary">Add New Part</a>

    <div id="app">  <!-- Vue app -->
        <div class="mt-3">
            <parts-index :initial-parts="{{ json_encode($parts, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_HEX_AMP | JSON_UNESCAPED_UNICODE) }}"></parts-index>
        </div>
    </div> <!-- Konec #app -->

    <?php /*
        <div class="mt-3">
            <table class="table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Serial Number</th>
                        <th>Car</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($parts as $part)
                        <tr>
                            <td>{{ $part->name }}</td>
                            <td>{{ $part->serialnumber }}</td>
                            <td>{{ $part->car->name }}</td>
                            <td>
                                <a href="{{ route('parts.show', $part) }}" class="btn btn-info me-2">View</a>
                                <a href="{{ route('parts.edit', $part) }}" class="btn btn-warning me-2">Edit</a>
                                <form action="{{ route('parts.destroy', $part) }}" method="POST" style="display: inline-block;">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger">Delete</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
    </div> */?>

@endsection

@section('scripts')
    <script src="{{ mix('js/app.js') }}"></script>
@endsection        

resources/views/parts/show.blade.php
{{-- resources/views/parts/show.blade.php --}}

@extends('layouts.app')

@section('title', 'View Part')

@section('content')
<div class="container mt-4">
    <h1>View Part</h1>
    <a href="{{ route('parts.index') }}" class="btn btn-secondary mb-3">Back to All Parts</a>
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">{{ $part->name }}</h5>
            <p class="card-text">
                Serial Number: {{ $part->serialnumber }}<br>
                Car: {{ $part->car->name }}
            </p>
        </div>
    </div>
</div>
@endsection