routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\LogoutController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\CarController;
use App\Http\Controllers\PartController;


Route::get('/', function () {return view('welcome');})->name('index');

Route::resource('cars', CarController::class);
Route::resource('parts', PartController::class);


/**
 * Authentification
 */
Route::group(['middleware' => ['guest']], function() {
    /**
     * Register Routes
     */
    Route::get('/register', [RegisterController::class, 'show'])->name('register.show');
    Route::post('/register', [RegisterController::class, 'register'])->name('register.perform');

    /**
     * Login Routes
     */
    Route::get('/login', [LoginController::class, 'show'])->name('login.show');
    Route::post('/login', [LoginController::class, 'login'])->name('login.perform');

});

Route::group(['middleware' => ['auth']], function() {
    /**
     * Logout Routes
     */
    Route::get('/logout', [LogoutController::class, 'perform'])->name('logout.perform');
});

app/Models/Car.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Car extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'registration_number', 'is_registered'];

    public function parts()
    {
        return $this->hasMany(Part::class);
    }

}

app/Http/Controllers/CarController.php
<?php

namespace App\Http\Controllers;

use App\Models\Car;
use Illuminate\Http\Request;

class CarController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //$cars = Car::all();
        $cars = Car::with('parts')->get();
        return view('cars.index', compact('cars'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('cars.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'name' => 'required',
            'registration_number' => 'required_if:is_registered,1',
            'is_registered' => 'required|boolean',
        ]);
    
        Car::create($validatedData);
    
        return redirect()->route('cars.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Car  $car
     * @return \Illuminate\Http\Response
     */
    public function show(Car $car)
    {
        return view('cars.show', compact('car'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Car  $car
     * @return \Illuminate\Http\Response
     */
    public function edit(Car $car)
    {
        return view('cars.edit', compact('car'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Car  $car
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Car $car)
    {
        $validatedData = $request->validate([
            'name' => 'required',
            'registration_number' => 'required_if:is_registered,true',
            'is_registered' => 'required|boolean',
        ]);
    
        $car->update($validatedData);
    
        return redirect()->route('cars.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Car  $car
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $car = Car::findOrFail($id);
        $car->delete();
        return response()->json(['message' => 'Car deleted successfully.']);
    }

}

resources/views/cars/create.blade.php
{{-- resources/views/cars/create.blade.php --}}

@extends('layouts.app')

@section('title', 'Add New Car')

@section('content')
<div class="container mt-4">
    <h1>Add New Car</h1>
    <form method="POST" action="{{ route('cars.store') }}">
        @csrf
        <input type="hidden" name="is_registered" value="0">            
        <div class="mb-3">
            <label for="name" class="form-label">Name</label>
            <input type="text" class="form-control" id="name" name="name" required>
        </div>
        <div class="mb-3">
            <label for="registration_number" class="form-label">Registration Number</label>
            <input type="text" class="form-control" id="registration_number" name="registration_number">
        </div>
        <div class="mb-3 form-check">
            <input type="checkbox" class="form-check-input" id="is_registered" name="is_registered" value="1">
            <label class="form-check-label" for="is_registered">Is Registered</label>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
@endsection

resources/views/cars/edit.blade.php
{{-- resources/views/cars/edit.blade.php --}}

@extends('layouts.app')

@section('title', 'Edit Car')

@section('content')
<div class="container mt-4">
    <h1>Edit Car</h1>
    <form method="POST" action="{{ route('cars.update', $car) }}">
        @csrf
        @method('PUT')
        <input type="hidden" name="is_registered" value="0">            
        <div class="mb-3">
            <label for="name" class="form-label">Name</label>
            <input type="text" class="form-control" id="name" name="name" value="{{ $car->name }}" required>
        </div>
        <div class="mb-3">
            <label for="registration_number" class="form-label">Registration Number</label>
            <input type="text" class="form-control" id="registration_number" name="registration_number" value="{{ $car->registration_number }}">
        </div>
        <div class="mb-3 form-check">
            <input type="checkbox" class="form-check-input" id="is_registered" name="is_registered" {{ $car->is_registered ? 'checked' : '' }} value="1">
            <label class="form-check-label" for="is_registered">Is Registered</label>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
@endsection

resources/views/cars/index.blade.php
{{-- resources/views/cars/index.blade.php --}}

@extends('layouts.app')

@section('title', 'Cars List')

@section('content')
    <h1>Cars</h1>
        <a href="{{ route('index') }}" class="btn btn-secondary me-2">Home</a>
        <a href="{{ route('parts.index') }}" class="btn btn-secondary me-2">View Parts</a>
        <a href="{{ route('cars.create') }}" class="btn btn-primary">Add New Car</a>
    
    <div id="app">  <!-- Vue app-->
        <div class="mt-3">
            <cars-index :initial-cars="{{ json_encode($cars, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_HEX_AMP | JSON_UNESCAPED_UNICODE) }}"></cars-index>
        </div>
    </div> <!-- Koniec #app -->

    <?php /*
    <div class="mt-3">
    <table class="table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Registration Number</th>
                        <th>Is Registered</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($cars as $car)
                        <tr>
                            <td>{{ $car->name }}</td>
                            <td>{{ $car->registration_number }}</td>
                            <td>{{ $car->is_registered ? 'Yes' : 'No' }}</td>
                            <td>
                                <a href="{{ route('cars.show', $car) }}" class="btn btn-info">View</a>
                                <a href="{{ route('cars.edit', $car) }}" class="btn btn-warning">Edit</a>
                                <form action="{{ route('cars.destroy', $car) }}" method="POST" style="display: inline-block;">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger">Delete</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
    </div> */?>
@endsection

@section('scripts')
    <script src="{{ mix('js/app.js') }}"></script>
@endsection